version: '3'
services:
  web:
      build: .
      image: felingato1992/kclases:tacho-test
      #image: felingato1992/kclases:tacho-test
      container_name: "tacho_test_container"
      env_file:
        - .env
      volumes:
        - ./app/:/usr/src/app
        - static_files:/usr/src/app/static
        - media_files:/usr/src/app/media
      restart: always
      ports:
      - 8000:8000
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/usr/share/nginx/html/static
      - media_files:/usr/share/nginx/html/media
      - letsencrypt:/etc/letsencrypt
      - certbot:/usr/share/nginx/html/cert/
    depends_on:
      - web

volumes:
  static_files:
  media_files:
  letsencrypt:
  certbot: